Repository thekavikumar/love-simple-ui, pull requests merged in 2023-05, with the labels that each got.

#25 [doc]: README file update
  README.md
Labels: GSSoC

#55 feat:add template
  .github/Pull_Req_template.md
  .github/issue_template/bug_report.md
  .github/issue_template/documentation.md
  .github/issue_template/feature_req.md
  .github/issue_template/question.md
Labels: GSSoC

#53 PR Template Closes#32
  .github/pull_request_template.md
Labels: GSSoC

#15 Added Alert component with different Type
  package-lock.json
  package.json
  src/Alert/AlertFun.stories.tsx
  src/Alert/index.tsx
  src/index.ts
Labels: GSSoC

#58 feat:fixed templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_req.md
  .github/ISSUE_TEMPLATE/question.md
Labels: GSSoC

#77 contributor graph added
  README.md
Labels: good first issue, GSSoC

#88 Creating a design system
  Design/Border radius.pdf
  Design/Colours.pdf
  Design/Design.md
  Design/Display Font.pdf
  Design/Elevation.pdf
  Design/Headings.pdf
  Design/Paragraph.pdf
Labels: GSSoC

#61 New Components are welcomed
  README.md
  config.babelrc
  jest.config.js
  package-lock.json
  package.json
  src/RadioButton/RadioButton.stories.tsx
  src/RadioButton/RadioButton.test.js
  src/RadioButton/RadioButton.tsx
  src/button/PrimaryButton.stories.tsx
  src/checkbox/checkbox.js
  tsconfig.json
Labels: GSSoC

#99 feat: add input fields
  src/index.ts
  src/input/Input.stories.tsx
  src/input/index.tsx
Labels: gssoc23, level3

#98 Updated README.md
  README.md
Labels: gssoc23, level1

#103 Added accordion component
  src/accordion/Accordion.stories.tsx
  src/accordion/index.tsx
  src/index.ts
Labels: gssoc23, level3
